name: Check for state machine comment
on:
  issue_comment:
    types: [created]
jobs:
  run-on-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}

      - name: Find changed files
        run: |
          # Find all JavaScript and TypeScript files in the pull request
          code_files=$(git diff --no-merges --name-only ${{ github.event.issue.pull_request.base.sha }} ${{ github.event.issue.pull_request.head.sha }} -- '*.js' '*.ts')
          # Output list of files being checked
          echo "Checking the following files:"
          echo "$code_files"
          
#        run: |
#          # Check if comment contains "Create state machine screenshot"
#          if [[ "${{ github.event.comment.body }}" =~ "Create state machine screenshot" ]]; then
#            # Find all JavaScript and TypeScript files in the issue
#            code_files=$(git diff --name-only origin/main...HEAD -- '*.js' '*.ts')
#            head_check=$(HEAD)
#            echo "$head_check"
#            # Output list of files being checked
#            echo "Checking the following files:"
#            echo "$code_files"
#            # Check for the presence of a state machine in each file
#            for file in $code_files; do
#              if grep -q "createMachine" "$file"; then
#                echo "State machine found in $file"
#                exit 1
#              fi
#            done
#          fi
