name: Check for state machine comment
on:
  issue_comment:
    types: [created]
jobs:
  run-on-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List changed files
        run: |
          # Get the current pull request number from the issue_comment event payload
          pr_number=$(jq --raw-output .issue.number $GITHUB_EVENT_PATH)
          # Fetch the pull request data and get the branch name
          branch_name=$(curl -s https://api.github.com/repos/${{ github.repository }}'/pulls/'$pr_number | jq --raw-output '.head.ref')
          # List the changed files in the branch
          git diff --name-only $branch_name
          
#        run: |
#          # Check if comment contains "Create state machine screenshot"
#          if [[ "${{ github.event.comment.body }}" =~ "Create state machine screenshot" ]]; then
#            # Find all JavaScript and TypeScript files in the issue
#            code_files=$(git diff --name-only origin/main...HEAD -- '*.js' '*.ts')
#            head_check=$(HEAD)
#            echo "$head_check"
#            # Output list of files being checked
#            echo "Checking the following files:"
#            echo "$code_files"
#            # Check for the presence of a state machine in each file
#            for file in $code_files; do
#              if grep -q "createMachine" "$file"; then
#                echo "State machine found in $file"
#                exit 1
#              fi
#            done
#          fi
