name: Check for state machine comment
on:
  issue_comment:
    types: [created]
jobs:
  run-on-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Get PR branch name
        id: branch_name
        run: echo "::set-output name=branch_name::$(jq -r '.issue.pull_request.head.ref' $GITHUB_EVENT_PATH)"

      - name: List changed files
        run: |
          echo "Changed files in branch ${{ steps.branch_name.outputs.branch_name }}:"
          git fetch origin ${{ steps.branch_name.outputs.branch_name }}
          git diff --name-only origin/${{ steps.branch_name.outputs.branch_name }}

#        run: |
#          # Check if comment contains "Create state machine screenshot"
#          if [[ "${{ github.event.comment.body }}" =~ "Create state machine screenshot" ]]; then
#            # Find all JavaScript and TypeScript files in the issue
#            code_files=$(git diff --name-only origin/main...HEAD -- '*.js' '*.ts')
#            head_check=$(HEAD)
#            echo "$head_check"
#            # Output list of files being checked
#            echo "Checking the following files:"
#            echo "$code_files"
#            # Check for the presence of a state machine in each file
#            for file in $code_files; do
#              if grep -q "createMachine" "$file"; then
#                echo "State machine found in $file"
#                exit 1
#              fi
#            done
#          fi
