name: "Deploy on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          ${{ github.event.issue.pull_request }}


#          # Find all Javascript and Typescript files in the pull request
#          code_files=$(git diff --name-only ${{ github.event.issue.pull_request.base.ref }}...${{ github.event.issue.pull_request.head.ref }} -- '*.js' '*.ts')
#          # Output list of files being checked
#          echo "Checking the following files:"
#          echo "$code_files"
#          # Check for the presence of a state machine in each file
#          for file in $code_files; do
#            if grep -q "createMachine" "$file"; then
#              echo "State machine found in $file"
#              exit 1
#            fi
#          done
