name: Check for state machine comment
on:
  issue_comment:
    types: [created]
jobs:
  run-on-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Check for state machine
        run: |
          # Find all JavaScript files in the pull request
          code_files=$(jq -r '.pull_request.files[] | select(.filename | endswith(".js")) | .filename' "$GITHUB_EVENT_PATH")
          # Output list of files being checked
          echo "Checking the following files:"
          echo "$code_files"
          # Check for the presence of a state machine in each file
          for file in $code_files; do
            if grep -q "createMachine" "$file"; then
              echo "State machine found in $file"
              exit 1
            fi
          done